language: python
python:
  - "3.7"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv travis_zones.yaml zones.yaml
  - mv travis_home-assistant_v2.db home-assistant_v2.db
  - mv travis_home-assistant.log home-assistant.log
  - rm -rf custom_components
  - mv travis_hacs_components/ custom_components/
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
